version: "3.9"

services:
  nginx:
    build:
      context: . # הקונטקסט הוא התיקייה הראשית
      dockerfile: Dockerfile.nginx # שם ה-Dockerfile של Nginx
    ports:
      - "80:80" # מיפוי פורטים
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # מיפוי ווליום של nginx.conf
    depends_on: # תלות בין שירותים
      - app1
      - app2
      - app3
    networks:
      - app-network

  app1:
    build:
      context: . # הקונטקסט הוא התיקייה הראשית
      dockerfile: Dockerfile.app # שם ה-Dockerfile של האפליקציה
    ports:
      - "5001:5000" # מיפוי פורטים
    volumes:
      - app_logs:/app/logs # מיפוי ווליום ללוגים
    depends_on:
      - db # תלות בשירות ה-db
    networks:
      - app-network

  app2:
    build:
      context: . # הקונטקסט הוא התיקייה הראשית
      dockerfile: Dockerfile.app # שם ה-Dockerfile של האפליקציה
    ports:
      - "5002:5000" # מיפוי פורטים
    volumes:
      - app_logs:/app/logs # מיפוי ווליום ללוגים
    depends_on:
      - db # תלות בשירות ה-db
    networks:
      - app-network

  app3:
    build:
      context: . # הקונטקסט הוא התיקייה הראשית
      dockerfile: Dockerfile.app # שם ה-Dockerfile של האפליקציה
    ports:
      - "5003:5000" # מיפוי פורטים
    volumes:
      - app_logs:/app/logs # מיפוי ווליום ללוגים
    depends_on:
      - db # תלות בשירות ה-db
    networks:
      - app-network

  db:
    image: mysql:latest # שימוש ב-image של MySQL
    environment: # הגדרת משתני סביבה
      MYSQL_ROOT_PASSWORD: my_root_password  # **חשוב מאוד לשנות!**
      MYSQL_DATABASE: my_database      # **חשוב מאוד לשנות!**
      MYSQL_USER: my_user                    # **חשוב מאוד לשנות!**
      MYSQL_PASSWORD: my_password            # **חשוב מאוד לשנות!**
    volumes:
      - db_data:/var/lib/mysql # מיפוי ווליום לנתונים
      - db_logs:/var/log/mysql # מיפוי ווליום ללוגים
    networks:
      - app-network

volumes: # הגדרת ווליומים
  app_logs:
  db_data:
  db_logs:

networks: # הגדרת רשתות
  app-network:
