version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  app1:
    build: ./app
    ports:
      - "5001:5000"
    volumes:
      - app_logs:/var/log/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://my_user:my_password@db:3306/app_db
      - SERVER_IP=app1
    restart: always
    networks:
      - app-network

  app2:
    build: ./app
    ports:
      - "5002:5000"
    volumes:
      - app_logs:/var/log/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://my_user:my_password@db:3306/app_db
      - SERVER_IP=app2
    restart: always
    networks:
      - app-network

  app3:
    build: ./app
    ports:
      - "5003:5000"
    volumes:
      - app_logs:/var/log/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://my_user:my_password@db:3306/app_db
      - SERVER_IP=app3
    restart: always
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=app_db
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql
    networks:
      - app-network

volumes:
  app_logs:
  db_data:
  db_logs:

networks:
  app-network:
